### ISSUE TITLE
[Feature Request] fuzzydir for fonts

### ISSUE THREAD

**Issue by Obegg** [sibwaf/mpv-scripts#11] opened 2023-03-26 20:14 UTC
Use case:
(Subtitles from [animetosho](https://animetosho.org/view/anime-chap-vinland-saga-season-1-bd-1080p.n1618595) as an example)
(Download by "All attachments")
-- Main folder 1 (TV Show)
--- Video example 1.mkv (Episode 1)
--- Secondary folder 2 (Subs)
---- Alt folder 3 (Episode 1)
---- Subtitle file.ass (Episode 1.ass)
---- Alt folder 4 (attachments)
----- Fonts (arial.ttf)

For subtitles this script works great, it finds the subtitle file in every directory there is.

I was hoping if the same could be for fonts

**Comment by sibwaf** [comment] 2023-03-26 20:35
It's a good idea, but doesn't really seem possible - I don't see any configuration options in mpv that would allow adding folders to be scanned for fonts (feel free to prove me wrong).

If my understanding is correct, mpv might be able to scan the "fonts" folder in the same directory as the video file (see https://mpv.io/manual/stable/#options-sub-font-provider), so you could try that.

While the script can theoretically copy/link the files to the correct directory so mpv sees them, that's a big no-no from me for this script.

**Comment by AdventurerRussia** [comment] 2023-03-27 03:32
There is a compiled player assembly and a script that allows you to pick up fonts only from the fonts folder, but the problem is that if you have several fonts folders, then it will only pick up fonts folders from one, as well as the restriction that the folder should be called fonts.
so it won't just happen with fonts that they will lie in any folder and be picked up by the script.
https://github.com/fbriere/mpv-scripts/tree/master/scripts
https://github.com/dyphire/mpv-winbuild/releases/tag/mpv_own-2023-02-28

**Comment by sibwaf** [comment] 2023-03-27 10:48
Right. In this case, I don't see too many reasons to implement this in fuzzydir.

1. A script for this functionality already exists, so you can use that whenever mpv releases a version which includes https://github.com/mpv-player/mpv/pull/9856 (or just build it yourself right now as it's already merged)
2. As it would be impossible to specify multiple directories, fuzzydir's main "ideology" to be dumb and just expand wildcards wouldn't be really enough. This could change a bit in the future for optimization purposes (like "don't add paths without subtitles in them to `sub-file-paths` so mpv doesn't try to scan them", which could probably improve startup times - needs testing)
3. Even if fuzzydir starts being a bit less dumb due to 2, it would have to track the currently selected subtitle track and dynamically adjust the directory with fonts, which is a bit too smart for my liking in case of this script

The only saving grace I can think of would be that fuzzydir keeps a cache of directory scan results, so it wouldn't have to waste time on rescanning it while searching for fonts.

Considering everything, won't fix for now, I guess. Feel free to continue the discussion though.

**Closed as not planned by sibwaf** 2023-03-27 10:48 UTC
